### ISSUE TITLE
'NoneType' object has no attribute 'SIGTERM'

### ISSUE THREAD

**Issue by GoooKuuu** [flowersteam/Grounding_LLMs_with_online_RL#1]
Hello, thank you so much for sharing this amazing work. I am using it for my project and I am encountering an error that I'm hoping you could help me with.

When I run `sbatch Symbolic-PPO.slurm`, got these error messages:

File "/data/users/xxx/Grounding_LLMs_with_online_RL/experiments/train_symbolic_ppo.py", line 353, in <module>
algo = SymbolicPPOAgent(envs, acmodel, args.frames_per_proc, args.discount, args.lr, args.beta1, args.beta2,
TypeError: Can't instantiate abstract class SymbolicPPOAgent with abstract method generate_trajectories
Exception ignored in: <function ParallelShapedEnv.del at 0x7f7e40689750>
Traceback (most recent call last):
File "/data/users/xxx/Grounding_LLMs_with_online_RL/babyai-text/babyai/babyai/shaped_env.py", line 188, in del
File "/home/xxx/.conda/envs/dlp/lib/python3.10/multiprocessing/process.py", line 133, in terminate
File "/home/xxx/.conda/envs/dlp/lib/python3.10/multiprocessing/popen_fork.py", line 57, in terminate
AttributeError: 'NoneType' object has no attribute 'SIGTERM'

I would greatly appreciate any help you could provide in resolving this issue. If there's any additional information you need from me, please let me know. Thank you in advance for your time and assistance.

**Comment by ClementRomac** [comment]
Hi,

My apologies for such a late response! We're glad our work is useful for you. 

Concerning your issue, there was a bug in the SymbolicPPOAgent (the `generate_trajectories` method wasn't implemented). I'm creating a PR to fix this.

**Comment by ClementRomac** [comment]
Could you please checkout the [`1-nonetype-object-has-no-attribute-sigterm`](https://github.com/flowersteam/Grounding_LLMs_with_online_RL/tree/1-nonetype-object-has-no-attribute-sigterm) and confirm this fixes your issue?

**Comment by GoooKuuu** [comment]
Thank you for your suggestion:) I checked out the `1-nonetype-object-has-no-attribute-sigterm` branch as you recommended, but I still encountered a similar issue with the following error message: 
Exception ignored in: <function ParallelShapedEnv.__del__ at 0x7f2dd3449000>
Traceback (most recent call last):
  File "/data/users/xxxxx/Grounding_LLMs_with_online_RL/babyai-text/babyai/babyai/shaped_env.py", line 188, in __del__
  File "/home/xxxx/dlp/lib/python3.10/multiprocessing/process.py", line 133, in terminate
  File "/home/xxxxx/dlp/lib/python3.10/multiprocessing/popen_fork.py", line 57, in terminate
AttributeError: 'NoneType' object has no attribute 'SIGTERM'

**Comment by ClementRomac** [comment]
While I'm investigating on this exception, it only occurs when the environment gets closed at the end of training. So that means that you should be able to perform your training anyway.

**Comment by qizhg** [comment]
Hi @GoooKuuu 
Did you solve this issue?
